<?php

// This file declares a managed database record of type "ReportInstance."
// The record will be automatically inserted, updated, or deleted from the
// database as appropriate. For more details, see "hook_civicrm_managed" at:
// http://wiki.civicrm.org/confluence/display/CRMDOC42/Hook+Reference

return array(
  array(
    'name' => 'CRM_Membershipreports_Form_Report: Membership Join Events last month',
    'entity' => 'ReportInstance',
    'params' =>
    array(
      'description' => 'Provides a list of direct members who joined last month, along with their membership status and membership details.',
      'form_values' => serialize(
          array(
            'fields' => array(
              'sort_name' => '1',
              'membership_type_id' => '1',
              'membership_start_date' => '1',
              'membership_end_date' => '1',
              'name' => '1',
            ),
            'sort_name_op' => 'has',
            'sort_name_value' => '',
            'is_deleted_op' => 'eq',
            'is_deleted_value' => '0',
            'id_min' => '',
            'id_max' => '',
            'id_op' => 'lte',
            'id_value' => '',
            'join_date_relative' => 'previous.month',
            'join_date_from' => '',
            'join_date_to' => '',
            'membership_start_date_relative' => '',
            'membership_start_date_from' => '',
            'membership_start_date_to' => '',
            'membership_end_date_relative' => '',
            'membership_end_date_from' => '',
            'membership_end_date_to' => '',
            'owner_membership_id_min' => '',
            'owner_membership_id_max' => '',
            'owner_membership_id_op' => 'nll',
            'owner_membership_id_value' => '',
            'tid_op' => 'in',
            'tid_value' => array(),
            'sid_op' => 'in',
            'sid_value' => array(),
            'receive_date_relative' => '',
            'receive_date_from' => '',
            'receive_date_to' => '',
            'financial_type_id_op' => 'in',
            'financial_type_id_value' => array(),
            'payment_instrument_id_op' => 'in',
            'payment_instrument_id_value' => array(),
            'currency_op' => 'in',
            'currency_value' => array(),
            'contribution_status_id_op' => 'in',
            'contribution_status_id_value' => array(),
            'total_amount_min' => '',
            'total_amount_max' => '',
            'total_amount_op' => 'lte',
            'total_amount_value' => '',
            'address_street_number_min' => '',
            'address_street_number_max' => '',
            'address_street_number_op' => 'lte',
            'address_street_number_value' => '',
            'address_street_name_min' => '',
            'address_street_name_max' => '',
            'address_street_name_op' => 'lte',
            'address_street_name_value' => '',
            'address_street_address_op' => 'has',
            'address_street_address_value' => '',
            'address_city_op' => 'has',
            'address_city_value' => '',
            'address_postal_code_min' => '',
            'address_postal_code_max' => '',
            'address_postal_code_op' => 'lte',
            'address_postal_code_value' => '',
            'address_postal_code_suffix_min' => '',
            'address_postal_code_suffix_max' => '',
            'address_postal_code_suffix_op' => 'lte',
            'address_postal_code_suffix_value' => '',
            'address_county_id_op' => 'in',
            'address_county_id_value' => array(),
            'address_state_province_id_op' => 'in',
            'address_state_province_id_value' => array(),
            'address_country_id_op' => 'in',
            'address_country_id_value' => array(),
            'tagid_op' => 'in',
            'tagid_value' => array(),
            'gid_op' => 'in',
            'gid_value' => array(),
            'group_bys' => array(
              'id' => '1',
            ),
            'order_bys' => array(
              1 => array(
                'column' => 'sort_name',
                'order' => 'ASC',
              ),
              2 => array(
                'column' => 'membership_type_id',
                'order' => 'ASC',
              ),
              3 => array(
                'column' => 'receive_date',
                'order' => 'DESC',
              ),
            ),
            'email_subject' => '',
            'email_to' => '',
            'email_cc' => '',
            'row_count' => '',
            'view_mode' => 'criteria',
            'cache_minutes' => '60',
            'parent_id' => '',
            'radio_ts' => '',
            'groups' => '',
          )
      ),
      'permission' => 'access CiviMember',
      'report_id' => 'member/detail',
      'title' => 'Membership Join Events last month',
      'version' => 3,
    ),
  ),
);
